---
# Source: siddhu-ms-k8-doc-helm-chart/templates/siddhu-namespace.yaml
kind: Namespace
apiVersion: v1
metadata:
  name: springboot-application
---
# Source: siddhu-ms-k8-doc-helm-chart/templates/springboot-docker-consumer.yaml
apiVersion: v1
kind: Service
metadata:
  name: siddhuconsumer
  namespace: springboot-application
  labels:
    service: springboot-docker-consumer
spec:
  type: NodePort
  selector:
    component: springboot-docker-consumer
  ports:
  - port: 8090
    targetPort: 8090
---
# Source: siddhu-ms-k8-doc-helm-chart/templates/springboot-docker-producer.yaml
apiVersion: v1
kind: Service
metadata:
  name: siddhuproducer
  namespace: springboot-application
  labels:
    service: springboot-docker-producer
spec:
  type: NodePort
  selector:
    component: springboot-docker-producer
  ports:
  - port: 8091
    targetPort: 8091
---
# Source: siddhu-ms-k8-doc-helm-chart/templates/springboot-docker-consumer.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-docker-consumer
  namespace: springboot-application
spec:
  selector:
    matchLabels:
      component: springboot-docker-consumer
  template:
    metadata:
      labels:
        component: springboot-docker-consumer
    spec:
      containers:
      - name: springboot-docker-consumer
        image: shdhumale/springboot-docker-consumer:latest
        env:
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 8090
          name: http
          protocol: TCP
---
# Source: siddhu-ms-k8-doc-helm-chart/templates/springboot-docker-producer.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-docker-producer
  namespace: springboot-application
spec:
  selector:
    matchLabels:
      component: springboot-docker-producer
  template:
    metadata:
      labels:
        component: springboot-docker-producer
    spec:
      containers:
      - name: springboot-docker-producer
        image: shdhumale/springboot-docker-producer:latest
        env:
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 8091
          name: http
          protocol: TCP
---
# Source: siddhu-ms-k8-doc-helm-chart/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "RELEASE-NAME-siddhu-ms-k8-doc-helm-chart-test-connection"
  labels:
    helm.sh/chart: siddhu-ms-k8-doc-helm-chart-0.1.0
    app.kubernetes.io/name: siddhu-ms-k8-doc-helm-chart
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['RELEASE-NAME-siddhu-ms-k8-doc-helm-chart:8090']
  restartPolicy: Never
