# Default values for siddhu-ms-k8-doc-helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

#by siddhu start[
namespace:
  name: springboot-application
  
springbootdockerproducerdeployment:
  name: springboot-docker-producer  
producerimage:
  repository: shdhumale/springboot-docker-producer  
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
springbootproducer:
  port: 8091  

producerservice:
  type: NodePort #by siddhu give the nodeport so that we can access it from out side.  
  port: 8091 #by siddhu expose to node 
  targetPort: 8091 #by siddhu App server listening on this port  
  containerPort: 8091
  
springbootdockerconsumerdeployment:
  name: springboot-docker-consumer  
consumerimage:
  repository: shdhumale/springboot-docker-consumer  
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
springbootconsumer:
  port: 8090  

service:
  type: NodePort #by siddhu give the nodeport so that we can access it from out side.  
  port: 8090 #by siddhu expose to node 
  targetPort: 8090 #by siddhu App server listening on this port  
  containerPort: 8090

 
#by siddhu start]